### ISSUE TITLE
Idea: social media / comms WG

### ISSUE THREAD

**Issue by jacobian** [django/dsf-working-groups#3]
One of the next groups we want to form is a social media / communications WG. Let's use this space to start talking about the scope, membership, etc etc.

**Comment by jcjudkins** [comment]
Thank you for the invite! Looking forward to working in this group! Perhaps start the discussion towards the scope of the workgroup. Do we start with defining the group's purpose?

**Comment by sarahboyce** [comment]
https://github.com/django/dsf-working-groups/pull/6 👍

**Comment by thibaudcolas** [comment]
Done in #6!
