### ISSUE TITLE
Process Suggestion: Discord for Working Groups to meet

### ISSUE THREAD

**Issue by nanorepublica** [django/dsf-working-groups#4]
We recently had a suggestion that the Django Discord server could be a potential meeting place for Working groups if they desired. 

Briefly Discord has fine-grain permissions/roles to ensure only members have access to the required channels (text and/or video/voice)

I would like to suggest that it be an option for asynchronous communication for a Working Group and perhaps the default for synchronous meetings. This would require a change under "[Proposing a working group](https://github.com/django/dsf-working-groups#proposing-a-working-group)" to include discord.

I would be happy to raise a PR to suggest the change

**Comment by jacobian** [comment]
> I would be happy to raise a PR to suggest the change

Please do, that sounds great.
